### ISSUE TITLE
Finalize GraphQL queries for MVP functionalities (visualization / ideogram)

### ISSUE THREAD

**Issue by suneettipirneni** [Visionome/frontend#7]

**Comment by APherwani** [comment]
@joeygiordano13 what does this mean?

**Comment by joeygiordano13** [comment]
@APherwani we need to ensure the queries work for getting cytoband locations as responses for search matches. For instance, we have a query that must provide an array of json objects containing cytoband locations for all search results (genes).

**Comment by APherwani** [comment]
@joeygiordano13 I'm including @Dylans123 here because that'll only happen when he repopulates the db.

**Comment by APherwani** [comment]
This is done.
